default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: blogger_github_development

test:
  <<: *default
  database: blogger_github_test

production:
  <<: *default
  database: blogger_github_production
  username: jollypro
  password: <%= ENV['BLOGGER_GITHUB_DATABASE_PASSWORD'] %>
